# Generated by Django 5.0.1 on 2024-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50)),
                ('Author_Name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
